### ISSUE TITLE
Simple way of getting solution/getting binary output

### ISSUE THREAD

**Issue by PixelNinja132** [JRIngram/maze-gen#70]
# Feature Request - Simple way of getting solution/getting binary output
## Describe the feature
An easy way to validate solutions or get a binary output to make them compatible with https://www.npmjs.com/package/maze-solver

## If this request is related to a problem, describe the problem
I have no easy way of validating a solution.

## Alternate solutions to the problem
Instead of adding a solving algorithm, you could output binary in rows to represent the maze. This would then make it compatible with https://www.npmjs.com/package/maze-solver

## Example implementations of similar features
https://www.npmjs.com/package/maze-solver

**Comment by JRIngram** [comment]
Hey @PixelNinja132, I've got a released lined up to be released soon and this won't be included in it it unfortunately. This is definitely that I can pick up for the next release though; also feel free to pick up if you like!

**Comment by JRIngram** [comment]
@PixelNinja132 this has been released as part of 3.1.1: https://github.com/JRIngram/maze-gen/releases/tag/v.3.1.1
